const TRIVIA_CATEGORIES = [
  { id: 'blandat', name: 'Blandat', icon: '\u{1F3B2}' },
  { id: 'geografi', name: 'Geografi', icon: '\u{1F30D}' },
  { id: 'vetenskap', name: 'Vetenskap', icon: '\u{1F52C}' },
  { id: 'historia', name: 'Historia', icon: '\u{1F4DC}' },
  { id: 'popkultur', name: 'Popkultur', icon: '\u{1F3AC}' },
  { id: 'fotboll', name: 'Fotboll', icon: '\u26BD' },
  { id: 'gaming', name: 'Gaming', icon: '\u{1F3AE}' },
  { id: 'sverige', name: 'Sverige', icon: '\u{1F1F8}\u{1F1EA}' }
];

const QUESTIONS = {
  geografi: [
    {question:"Vilken är Europas längsta flod?",options:["Donau","Volga","Rhen","Elbe"],correctAnswer:1},
    {question:"Vilket land har flest invånare i världen?",options:["USA","Indien","Kina","Indonesien"],correctAnswer:1},
    {question:"Vad heter Japans högsta berg?",options:["Fuji","Mount Everest","K2","Mont Blanc"],correctAnswer:0},
    {question:"Vilken är världens största öken?",options:["Gobi","Sahara","Antarktis","Kalahari"],correctAnswer:2},
    {question:"Vilket land gränsar inte till Tyskland?",options:["Polen","Frankrike","Belgien","Italien"],correctAnswer:3},
    {question:"Vad heter huvudstaden i Australien?",options:["Sydney","Melbourne","Canberra","Brisbane"],correctAnswer:2},
    {question:"Vilket hav ligger mellan Europa och Afrika?",options:["Röda havet","Svarta havet","Medelhavet","Östersjön"],correctAnswer:2},
    {question:"I vilket land ligger Machu Picchu?",options:["Peru","Chile","Colombia","Argentina"],correctAnswer:0},
    {question:"Vilken amerikansk delstat är störst till ytan?",options:["Texas","Kalifornien","Alaska","Montana"],correctAnswer:2},
    {question:"Vad heter världens djupaste sjö?",options:["Viktoriasjön","Bajkalsjön","Titicacasjön","Kaspiska havet"],correctAnswer:1},
    {question:"Vilket land har formen av en stövel?",options:["Spanien","Italien","Grekland","Turkiet"],correctAnswer:1},
    {question:"I vilken världsdel ligger Madagaskar?",options:["Asien","Sydamerika","Oceanien","Afrika"],correctAnswer:3},
    {question:"Vad heter huvudstaden i Kanada?",options:["Toronto","Vancouver","Ottawa","Montreal"],correctAnswer:2},
    {question:"Vilken är världens minsta självständiga stat?",options:["Monaco","San Marino","Vatikanstaten","Liechtenstein"],correctAnswer:2},
    {question:"Vilken flod rinner genom London?",options:["Themsen","Seine","Tiber","Liffey"],correctAnswer:0},
    {question:"Vilket av följande länder ligger i Sydamerika?",options:["Kuba","Surinam","Jamaica","Costa Rica"],correctAnswer:1},
    {question:"Vad heter Nya Zeelands huvudstad?",options:["Auckland","Wellington","Christchurch","Hamilton"],correctAnswer:1},
    {question:"Vilket land har flest öar i världen?",options:["Sverige","Indonesien","Filippinerna","Finland"],correctAnswer:0},
    {question:"I vilket land ligger staden Marrakech?",options:["Egypten","Marocko","Algeriet","Tunisien"],correctAnswer:1},
    {question:"Vad heter bergskedjan som skiljer Europa från Asien?",options:["Alperna","Himalaya","Kaukasus","Uralbergen"],correctAnswer:3},
    {question:"Vilken är Sydamerikas längsta flod?",options:["Amazonfloden","Orinoco","Paraná","São Francisco"],correctAnswer:0},
    {question:"Vilket av dessa länder har inte euro som valuta?",options:["Spanien","Schweiz","Tyskland","Italien"],correctAnswer:1},
    {question:"Vad heter huvudstaden i Sydkorea?",options:["Pyongyang","Seoul","Tokyo","Peking"],correctAnswer:1},
    {question:"I vilket hav ligger Maldiverna?",options:["Stilla havet","Atlanten","Indiska oceanen","Medelhavet"],correctAnswer:2},
    {question:"Vilket är det till ytan största landet i Afrika?",options:["Sudan","Algeriet","Kongo-Kinshasa","Libyen"],correctAnswer:1},
    {question:"Vilket nordiskt land kallas 'De tusen sjöarnas land'?",options:["Norge","Sverige","Island","Finland"],correctAnswer:3},
    {question:"Vilken av dessa städer ligger inte i USA?",options:["Miami","Toronto","Chicago","Houston"],correctAnswer:1},
    {question:"Vad heter sundet mellan Sverige och Danmark?",options:["Skagerrak","Kattegatt","Öresund","Bosporen"],correctAnswer:2},
    {question:"I vilket land ligger Taj Mahal?",options:["Indien","Pakistan","Bangladesh","Nepal"],correctAnswer:0},
    {question:"Vilken stad är världens nordligaste huvudstad?",options:["Helsingfors","Reykjavik","Oslo","Stockholm"],correctAnswer:1},
    {question:"Vad heter den största ön i Medelhavet?",options:["Sardinien","Cypern","Kreta","Sicilien"],correctAnswer:3},
    {question:"Vilken färg har den översta randen i Tysklands flagga?",options:["Röd","Svart","Gul","Vit"],correctAnswer:1},
    {question:"Vilket land består av England, Skottland, Wales och Nordirland?",options:["Irland","Storbritannien","Island","Frankrike"],correctAnswer:1},
    {question:"Vad heter världens längsta flod?",options:["Amazonfloden","Kongo","Yangtze","Nilen"],correctAnswer:3},
    {question:"I vilken stad kan man besöka Colosseum?",options:["Aten","Rom","Neapel","Milano"],correctAnswer:1},
    {question:"Vilken kontinent är kallast?",options:["Asien","Nordamerika","Antarktis","Europa"],correctAnswer:2},
    {question:"Vilket av dessa länder är en ögrupp?",options:["Tyskland","Filippinerna","Polen","Brasilien"],correctAnswer:1},
    {question:"Vad heter huvudstaden i Argentina?",options:["Santiago","Bogotá","Lima","Buenos Aires"],correctAnswer:3},
    {question:"Vilken bergskedja ligger i Sydamerika?",options:["Anderna","Alperna","Klippiga bergen","Atlasbergen"],correctAnswer:0},
    {question:"Vilket land är känt för sina tulpaner och väderkvarnar?",options:["Belgien","Tyskland","Nederländerna","Danmark"],correctAnswer:2},
    {question:"Vad heter sjön som ligger vid Chicago?",options:["Lake Superior","Lake Michigan","Lake Huron","Lake Erie"],correctAnswer:1},
    {question:"Vilken är Afrikas högsta punkt?",options:["Mount Kenya","Kilimanjaro","Ras Dashen","Mount Meru"],correctAnswer:1},
    {question:"Vilket av dessa länder ligger i Centralamerika?",options:["Ecuador","Bolivia","Panama","Uruguay"],correctAnswer:2},
    {question:"Vad heter Turkiets största stad?",options:["Ankara","Izmir","Antalya","Istanbul"],correctAnswer:3},
    {question:"Vilket hav ligger öster om Italien?",options:["Joniska havet","Adriatiska havet","Egeiska havet","Tyrrenska havet"],correctAnswer:1},
    {question:"I vilket land ligger staden Kyoto?",options:["Kina","Japan","Sydkorea","Vietnam"],correctAnswer:1},
    {question:"Vilken huvudstad genomskärs av floden Donau?",options:["Prag","Budapest","Warszawa","Berlin"],correctAnswer:1},
    {question:"Vilken ö är känd för sina stora stenstatyer, moai?",options:["Påskön","Galapagosöarna","Tahiti","Fiji"],correctAnswer:0},
    {question:"Vilket europeiskt land har gräns mot Ryssland?",options:["Sverige","Tyskland","Finland","Österrike"],correctAnswer:2},
    {question:"Vilken afrikansk flod är känd för Victoriafallen?",options:["Nilen","Kongo","Niger","Zambezi"],correctAnswer:3}
  ],
  vetenskap: [
    {question:"Vilken planet är närmast solen?",options:["Venus","Mars","Merkurius","Jorden"],correctAnswer:2},
    {question:"Vilken gas är vanligast i jordens atmosfär?",options:["Syre","Kväve","Koldioxid","Väte"],correctAnswer:1},
    {question:"Vem formulerade relativitetsteorin?",options:["Isaac Newton","Albert Einstein","Niels Bohr","Galileo Galilei"],correctAnswer:1},
    {question:"Vad står DNA för?",options:["Deoxyribonukleinsyra","Diribonukleinsyra","Deoxynukleinsyra","Di-nukleinsyra"],correctAnswer:0},
    {question:"Vilket kemiskt tecken har guld?",options:["Go","Ag","Au","Gd"],correctAnswer:2},
    {question:"Vad mäts i enheten Ampere?",options:["Spänning","Resistans","Elektrisk ström","Effekt"],correctAnswer:2},
    {question:"Vilken av följande är en ädelgas?",options:["Syre","Neon","Väte","Klor"],correctAnswer:1},
    {question:"Vad heter vår galax?",options:["Andromeda","Vintergatan","Magellanska molnen","Orion"],correctAnswer:1},
    {question:"Vilket organ pumpar runt blodet i kroppen?",options:["Levern","Lungorna","Hjärtat","Njurarna"],correctAnswer:2},
    {question:"Vad kallas en vinkel som är exakt 90 grader?",options:["Spetsig","Trubbig","Rät","Rak"],correctAnswer:2},
    {question:"Vilket djur är det största nu levande?",options:["Elefant","Vithaj","Kaskelot","Blåval"],correctAnswer:3},
    {question:"Vilken färg har kortast våglängd i det synliga spektrumet?",options:["Röd","Grön","Blå","Violett"],correctAnswer:3},
    {question:"Vem uppfann glödlampan?",options:["Nikola Tesla","Alexander Graham Bell","Thomas Edison","Guglielmo Marconi"],correctAnswer:2},
    {question:"Vilket är det hårdaste naturliga materialet?",options:["Kvarts","Diamant","Grafen","Titan"],correctAnswer:1},
    {question:"Hur många kromosomer har en människa normalt?",options:["42","44","46","48"],correctAnswer:2},
    {question:"Vad kallas processen där växter gör mat av solljus?",options:["Respiration","Fotosyntes","Transpiration","Metabolism"],correctAnswer:1},
    {question:"Vilket organ renar blodet från gifter?",options:["Njurarna","Levern","Mjälten","Bukspottkörteln"],correctAnswer:1},
    {question:"Vad är fryspunkten för vatten i Fahrenheit?",options:["0","32","100","212"],correctAnswer:1},
    {question:"Vilken planet kallas för 'Den röda planeten'?",options:["Jupiter","Saturnus","Mars","Venus"],correctAnswer:2},
    {question:"Vilket grundämne har atomnummer 1?",options:["Helium","Syre","Kol","Väte"],correctAnswer:3},
    {question:"Vad är ljudets hastighet i luft (ungefär)?",options:["340 m/s","1500 m/s","300 000 km/s","120 m/s"],correctAnswer:0},
    {question:"Vilken svensk forskare skapade den moderna systematiken?",options:["Alfred Nobel","Carl von Linné","Anders Celsius","Jöns Jacob Berzelius"],correctAnswer:1},
    {question:"Vilken sjukdom orsakade digerdöden?",options:["Kolera","Smittkoppor","Pest","Tuberkulos"],correctAnswer:2},
    {question:"Vilken del av hjärnan styr balansen?",options:["Stora hjärnan","Lillhjärnan","Hjärnstammen","Hjärnbarken"],correctAnswer:1},
    {question:"Vilken av dessa är en reptil?",options:["Grodan","Sköldpaddan","Salamandern","Paddan"],correctAnswer:1},
    {question:"Vad är H2O ett kemiskt namn för?",options:["Salt","Socker","Vatten","Alkohol"],correctAnswer:2},
    {question:"Vilken metall är flytande vid rumstemperatur?",options:["Bly","Zink","Kvicksilver","Koppar"],correctAnswer:2},
    {question:"Vad kallas studiet av svampar?",options:["Mykologi","Botanik","Zoologi","Ekologi"],correctAnswer:0},
    {question:"Vilken typ av stjärna är vår sol?",options:["Röd jätte","Vit dvärg","Gul dvärg","Neutronstjärna"],correctAnswer:2},
    {question:"Vilken kraft håller oss kvar på marken?",options:["Friktion","Magnetism","Gravitation","Elektricitet"],correctAnswer:2},
    {question:"Vem skrev 'Om arternas uppkomst'?",options:["Gregor Mendel","Louis Pasteur","Charles Darwin","Sigmund Freud"],correctAnswer:2},
    {question:"Vad mäts med en seismograf?",options:["Vindhastighet","Jordbävningar","Lufttryck","Temperatur"],correctAnswer:1},
    {question:"Vilken blodgrupp är en universalgivare?",options:["A-","B+","AB+","O-"],correctAnswer:3},
    {question:"Vad är jordens enda naturliga satellit?",options:["Månen","Phobos","Titan","Europa"],correctAnswer:0},
    {question:"Vilket organ producerar insulin?",options:["Levern","Bukspottkörteln","Sköldkörteln","Njurarna"],correctAnswer:1},
    {question:"Vilken svamp upptäcktes penicillin från?",options:["Champinjon","Flugsvamp","Penselmögel","Jästsvamp"],correctAnswer:2},
    {question:"Vad är pH-värdet för rent vatten?",options:["5","7","9","14"],correctAnswer:1},
    {question:"Hur många ben har en insekt?",options:["4","6","8","10"],correctAnswer:1},
    {question:"Vem upptäckte radioaktiviteten hos uran?",options:["Marie Curie","Henri Becquerel","Wilhelm Röntgen","Enrico Fermi"],correctAnswer:1},
    {question:"Vad kallas den positivt laddade partikeln i en atomkärna?",options:["Elektron","Neutron","Proton","Foton"],correctAnswer:2},
    {question:"Vilket vitamin fylls på när vi är i solen?",options:["A-vitamin","B-vitamin","C-vitamin","D-vitamin"],correctAnswer:3},
    {question:"Vilken tidsålder kom efter stenåldern?",options:["Bronsåldern","Järnåldern","Medeltiden","Antiken"],correctAnswer:0},
    {question:"Vilken av dessa fåglar kan inte flyga?",options:["Struts","Örn","Svala","Albatross"],correctAnswer:0},
    {question:"Vilket är kroppens största organ?",options:["Levern","Hjärnan","Huden","Tjocktarmen"],correctAnswer:2},
    {question:"Vad studerar en paleontolog?",options:["Stjärnor","Fossiler","Väder","Språk"],correctAnswer:1},
    {question:"Vad kallas rädsla för spindlar?",options:["Klaustrofobi","Agorafobi","Arachnofobi","Akrofobi"],correctAnswer:2},
    {question:"Vilken gas används i ballonger för att de ska flyga?",options:["Väte","Syre","Helium","Kväve"],correctAnswer:2},
    {question:"Vilket moln är känt som åskmoln?",options:["Cirrus","Stratus","Cumulonimbus","Altocumulus"],correctAnswer:2},
    {question:"Vem formulerade rörelselagarna?",options:["Albert Einstein","Isaac Newton","Johannes Kepler","Galileo Galilei"],correctAnswer:1},
    {question:"Vad är det kemiska namnet för koksalt?",options:["Natriumklorid","Kalciumkarbonat","Kaliumnitrat","Magnesiumsulfat"],correctAnswer:0},
    {question:"Hur många ben har en vuxen människa normalt?",options:["206","195","215","180"],correctAnswer:0},
    {question:"Vilken gas andas vi in för att överleva?",options:["Koldioxid","Syre","Kväve","Väte"],correctAnswer:1},
    {question:"Vad är pi ungefär lika med?",options:["2,71","1,61","3,14","3,24"],correctAnswer:2},
    {question:"Vad heter den största planeten i vårt solsystem?",options:["Jupiter","Saturnus","Uranus","Neptunus"],correctAnswer:0},
    {question:"Vilket ämne gör att växter är gröna?",options:["Karoten","Klorofyll","Melanin","Hemoglobin"],correctAnswer:1},
    {question:"Hur många hjärtan har en bläckfisk?",options:["Tre","Ett","Fyra","Två"],correctAnswer:0},
    {question:"Vilken blodgrupp är den vanligaste i Sverige?",options:["A","B","AB","0"],correctAnswer:0},
    {question:"Vad kallas en triangel där alla sidor är lika långa?",options:["Rätvinklig","Likbent","Liksidig","Trubbvinklig"],correctAnswer:2},
    {question:"Vad är vattnets kokpunkt i Celsius?",options:["50","150","200","100"],correctAnswer:3},
    {question:"Vem upptäckte penicillinet?",options:["Alexander Fleming","Marie Curie","Louis Pasteur","Robert Koch"],correctAnswer:0},
    {question:"Vilket är det minsta benet i människokroppen?",options:["Hammaren","Stigbygeln","Städet","Båtbenet"],correctAnswer:1},
    {question:"Vilken är vår närmaste stjärna efter solen?",options:["Sirius","Betelgeuse","Vega","Proxima Centauri"],correctAnswer:3},
    {question:"Vad är det kemiska tecknet för järn?",options:["Ir","Fe","In","Fr"],correctAnswer:1},
    {question:"Vilket organ producerar galla?",options:["Njuren","Bukspottskörteln","Levern","Mjälten"],correctAnswer:2},
    {question:"Vad kallas den del av ögat som ger det dess färg?",options:["Regnbågshinna","Hornhinna","Pupill","Näthinna"],correctAnswer:0},
    {question:"Vem uppfann dynamiten?",options:["Thomas Edison","Alfred Nobel","Nikola Tesla","Guglielmo Marconi"],correctAnswer:1},
    {question:"Vad kallas vetenskapen om ljus och dess egenskaper?",options:["Optik","Termodynamik","Akustik","Mekanik"],correctAnswer:0},
    {question:"Vad är absolut nollpunkt i Celsius?",options:["-100","-250,5","-360","-273,15"],correctAnswer:3},
    {question:"Hur många planeter finns det i vårt solsystem?",options:["Nio","Sju","Åtta","Tio"],correctAnswer:2},
    {question:"Vad kallas ljud vars frekvens är högre än vi kan höra?",options:["Ultraljud","Infraljud","Ekolod","Mikrovåg"],correctAnswer:0},
    {question:"Vilken fågel lägger de största äggen?",options:["Emu","Struts","Pingvin","Kivi"],correctAnswer:1},
    {question:"Vilken del av cellen fungerar som dess kraftverk?",options:["Mitokondrien","Ribosomen","Kärnan","Golgiapparaten"],correctAnswer:0},
    {question:"Hur lång tid tar det för jorden att snurra runt sin egen axel?",options:["12 timmar","365 dagar","1 månad","24 timmar"],correctAnswer:3},
    {question:"Vilket matematiskt begrepp beskriver lutningen på en kurva?",options:["Integral","Derivata","Funktion","Logaritm"],correctAnswer:1},
    {question:"Vad kallas läran om jordens uppbyggnad?",options:["Meteorologi","Biologi","Geologi","Astronomi"],correctAnswer:2},
    {question:"Vilken typ av blodkärl leder blod bort från hjärtat?",options:["Vener","Artärer","Kapillärer","Aortan"],correctAnswer:1},
    {question:"Vad är det vanligaste grundämnet i universum?",options:["Syre","Väte","Helium","Kol"],correctAnswer:1},
    {question:"Hur många procent av jorden är täckt av vatten?",options:["Cirka 71","Cirka 50","Cirka 85","Cirka 60"],correctAnswer:0},
    {question:"Vad heter partikeln i atomen som har negativ laddning?",options:["Proton","Neutron","Positron","Elektron"],correctAnswer:3},
    {question:"Vilken syra finns i människans magsäck?",options:["Svavelsyra","Mjölksyra","Saltsyra","Citronsyra"],correctAnswer:2},
    {question:"Vad är ett ljusår en enhet för?",options:["Avstånd","Tid","Hastighet","Ljusstyrka"],correctAnswer:0}
  ],
  historia: [
    {question:"Vilket år startade första världskriget?",options:["1912","1914","1918","1939"],correctAnswer:1},
    {question:"Vem var den första presidenten i USA?",options:["Thomas Jefferson","Abraham Lincoln","George Washington","John Adams"],correctAnswer:2},
    {question:"Vilket land skickade första människan ut i rymden?",options:["USA","Sovjetunionen","Kina","Storbritannien"],correctAnswer:1},
    {question:"När föll Berlinmuren?",options:["1987","1989","1991","1993"],correctAnswer:1},
    {question:"Vilken fransk drottning avrättades under franska revolutionen?",options:["Katarina av Medici","Jeanne d'Arc","Marie Antoinette","Eleonora av Akvitanien"],correctAnswer:2},
    {question:"Vilken farao är känd för sin välbevarade grav?",options:["Kleopatra","Ramses II","Tutankhamon","Akhenaton"],correctAnswer:2},
    {question:"Vem upptäckte sjövägen till Indien?",options:["Christofer Columbus","Vasco da Gama","Ferdinand Magellan","James Cook"],correctAnswer:1},
    {question:"Vilket krig pågick mellan 1939 och 1945?",options:["Första världskriget","Vietnamkriget","Koreakriget","Andra världskriget"],correctAnswer:3},
    {question:"Vilket imperium styrdes av Julius Caesar?",options:["Grekiska","Osmanska","Romerska","Brittiska"],correctAnswer:2},
    {question:"Vem var Sovjetunionens ledare under andra världskriget?",options:["Vladimir Lenin","Nikita Chrusjtjov","Josef Stalin","Michail Gorbatjov"],correctAnswer:2},
    {question:"Vad hette fartyget som sjönk på sin jungfrufärd 1912?",options:["Lusitania","Titanic","Britannic","Bismarck"],correctAnswer:1},
    {question:"Vilken händelse startade franska revolutionen?",options:["Skräckväldet","Stormningen av Bastiljen","Slaget vid Waterloo","Avrättningen av kungen"],correctAnswer:1},
    {question:"Vem mördade Abraham Lincoln?",options:["Lee Harvey Oswald","John Wilkes Booth","Charles Guiteau","Leon Czolgosz"],correctAnswer:1},
    {question:"Vilket europeiskt land koloniserade Brasilien?",options:["Spanien","Frankrike","Portugal","Nederländerna"],correctAnswer:2},
    {question:"Vad hette atombomben som släpptes över Hiroshima?",options:["Fat Man","Little Boy","Tsar Bomba","Trinity"],correctAnswer:1},
    {question:"Vilken känd ledare förknippas med saltmarschen?",options:["Nelson Mandela","Martin Luther King Jr.","Mahatma Gandhi","Dalai Lama"],correctAnswer:2},
    {question:"Vilket år dog Karl XII?",options:["1632","1718","1792","1810"],correctAnswer:1},
    {question:"Vilket land tillhörde Inkariket?",options:["Mexiko","Peru","Egypten","Grekland"],correctAnswer:1},
    {question:"Vem var Storbritanniens premiärminister under andra världskriget?",options:["Neville Chamberlain","Clement Attlee","Winston Churchill","Margaret Thatcher"],correctAnswer:2},
    {question:"Vad kallades det antika Roms gladiatorarena?",options:["Pantheon","Colosseum","Forum Romanum","Cirkus Maximus"],correctAnswer:1},
    {question:"Vem skrev Kommunistiska manifestet tillsammans med Engels?",options:["Vladimir Lenin","Lev Trotskij","Karl Marx","Joseph Stalin"],correctAnswer:2},
    {question:"I vilken stad satt Nelson Mandela fängslad på Robben Island?",options:["Johannesburg","Kapstaden","Durban","Pretoria"],correctAnswer:1},
    {question:"Vilket krig förlorade Ryssland 1904-1905?",options:["Krimkriget","Rysk-japanska kriget","Första världskriget","Nordiska kriget"],correctAnswer:1},
    {question:"Vad hette systemet med rassegregation i Sydafrika?",options:["Apartheid","Segregation","Slaveri","Kolonialism"],correctAnswer:0},
    {question:"Vem var Rysslands sista tsar?",options:["Peter den store","Ivan den förskräcklige","Nikolaj II","Alexander III"],correctAnswer:2},
    {question:"Vilket år landsteg människan på månen första gången?",options:["1965","1969","1972","1959"],correctAnswer:1},
    {question:"Vilket århundrade skedde den industriella revolutionen?",options:["1600-talet","1700-talet","1800-talet","1900-talet"],correctAnswer:1},
    {question:"Vad hette mongolernas berömda ledare på 1200-talet?",options:["Djingis Khan","Kublai Khan","Attila","Timur Lenk"],correctAnswer:0},
    {question:"Vilket krig utspelade sig mellan Nord och Syd i USA?",options:["Oberoendekriget","Inbördeskriget","Mexikanska kriget","Spansk-amerikanska kriget"],correctAnswer:1},
    {question:"Vilken drottning styrde England under guldåldern på 1500-talet?",options:["Katarina av Aragonien","Maria I","Elisabet I","Viktoria"],correctAnswer:2},
    {question:"Vad hette Tysklands första demokratiska republik?",options:["Förbundsrepubliken","Weimarrepubliken","Tredje riket","Bismarckriket"],correctAnswer:1},
    {question:"Vem ledde det framgångsrika slavupproret på Haiti?",options:["Toussaint Louverture","Simón Bolívar","José de San Martín","Fidel Castro"],correctAnswer:0},
    {question:"Vilket år skedde terrorattackerna mot World Trade Center?",options:["1999","2000","2001","2002"],correctAnswer:2},
    {question:"Vad var kodenamnet för invasionen av Normandie?",options:["Operation Barbarossa","Operation Overlord","Operation Market Garden","Operation Torch"],correctAnswer:1},
    {question:"Vem var den första kvinnliga nobelpristagaren?",options:["Rosalind Franklin","Marie Curie","Jane Addams","Selma Lagerlöf"],correctAnswer:1},
    {question:"Vilken stad delades av en mur under Kalla kriget?",options:["Moskva","Warszawa","Berlin","Wien"],correctAnswer:2},
    {question:"Vad hette fartyget som förde pilgrimerna till Nordamerika?",options:["Santa Maria","Mayflower","Endeavour","Victoria"],correctAnswer:1},
    {question:"Vilken händelse utlöste 30-åriga kriget?",options:["Skottet i Sarajevo","Defenestrationen i Prag","Bartholomeinatten","Middagen i Nyköping"],correctAnswer:1},
    {question:"Vem mördades i Sarajevo 1914?",options:["Tsar Nikolaj II","Abraham Lincoln","Franz Ferdinand","Julius Caesar"],correctAnswer:2},
    {question:"Vilken organisation grundades 1945 för att bevara världsfreden?",options:["Nationernas Förbund","NATO","Förenta Nationerna","Europeiska Unionen"],correctAnswer:2},
    {question:"Vad hette den svenske diplomat som räddade judar i Budapest?",options:["Folke Bernadotte","Dag Hammarskjöld","Raoul Wallenberg","Harald Edelstam"],correctAnswer:2},
    {question:"Vem var känd som 'Jungfrun av Orléans'?",options:["Jeanne d'Arc","Marie Antoinette","Katarina den stora","Elisabet I"],correctAnswer:0},
    {question:"Vilket fördrag avslutade första världskriget?",options:["Wienkongressen","Versaillesfreden","Westfaliska freden","Trianonfördraget"],correctAnswer:1},
    {question:"Vad kallades de skandinaviska sjöfararna under 800-1000-talet?",options:["Kelter","Goter","Vikingar","Hunner"],correctAnswer:2},
    {question:"Vilken amerikansk president avgick pga Watergateskandalen?",options:["John F. Kennedy","Lyndon B. Johnson","Richard Nixon","Gerald Ford"],correctAnswer:2},
    {question:"Vilket land var först med att ge kvinnor rösträtt?",options:["Nya Zeeland","Sverige","Storbritannien","USA"],correctAnswer:0},
    {question:"Vad hette Kubas ledare från 1959 till 2008?",options:["Che Guevara","Fidel Castro","Raúl Castro","Fulgencio Batista"],correctAnswer:1},
    {question:"Vem uppfann boktryckarkonsten i Europa?",options:["Leonardo da Vinci","Johannes Gutenberg","Galileo Galilei","Isaac Newton"],correctAnswer:1},
    {question:"Vilken sjukdom drabbade Europa hårt på 1300-talet?",options:["Digerdöden","Spanska sjukan","Kolera","Smittkoppor"],correctAnswer:0},
    {question:"Vad kallades turerna till det Heliga landet beordrade av Påven?",options:["Pilgrimsresor","Korståg","Missioner","Inkvisitionen"],correctAnswer:1}
  ],
  popkultur: [
    {question:"Vem spelar Jack Dawson i filmen Titanic?",options:["Brad Pitt","Tom Cruise","Leonardo DiCaprio","Matt Damon"],correctAnswer:2},
    {question:"Vilken artist kallas 'The King of Pop'?",options:["Elvis Presley","Michael Jackson","Prince","Freddie Mercury"],correctAnswer:1},
    {question:"Vad heter den fiktiva kontinenten i Game of Thrones?",options:["Middle-earth","Westeros","Narnia","Hogwarts"],correctAnswer:1},
    {question:"Vem sjöng 'Rolling in the Deep'?",options:["Beyoncé","Adele","Lady Gaga","Taylor Swift"],correctAnswer:1},
    {question:"Vilken skådespelare spelar Iron Man?",options:["Chris Evans","Chris Hemsworth","Mark Ruffalo","Robert Downey Jr."],correctAnswer:3},
    {question:"Vilket år släpptes den första Star Wars-filmen?",options:["1973","1977","1980","1983"],correctAnswer:1},
    {question:"Vilken reality-familj har serien 'Keeping Up with the...'?",options:["Osbournes","Kardashians","Hadids","Jenners"],correctAnswer:1},
    {question:"Vad heter huvudkaraktären i Breaking Bad?",options:["Jesse Pinkman","Saul Goodman","Walter White","Hank Schrader"],correctAnswer:2},
    {question:"Vem regisserade Pulp Fiction?",options:["Steven Spielberg","Martin Scorsese","Quentin Tarantino","Christopher Nolan"],correctAnswer:2},
    {question:"Vilken artist sjunger 'Blank Space'?",options:["Ariana Grande","Katy Perry","Miley Cyrus","Taylor Swift"],correctAnswer:3},
    {question:"Vilken svensk artist vann Eurovision med 'Euphoria'?",options:["Carola","Loreen","Måns Zelmerlöw","Charlotte Perrelli"],correctAnswer:1},
    {question:"Vad heter Harry Potters uggla?",options:["Crookshanks","Scabbers","Hedwig","Fawkes"],correctAnswer:2},
    {question:"Vilken streamingtjänst producerade Stranger Things?",options:["Amazon Prime","Hulu","HBO","Netflix"],correctAnswer:3},
    {question:"Vem skapade The Simpsons?",options:["Seth MacFarlane","Matt Groening","Trey Parker","Mike Judge"],correctAnswer:1},
    {question:"Vilken popstjärna har fans som kallas 'Little Monsters'?",options:["Billie Eilish","Lady Gaga","Dua Lipa","Rihanna"],correctAnswer:1},
    {question:"Vad heter skurken i Lejonkungen?",options:["Mufasa","Simba","Scar","Jafar"],correctAnswer:2},
    {question:"Vem spelade huvudrollen i Forrest Gump?",options:["Tom Hanks","Harrison Ford","Bill Murray","Robin Williams"],correctAnswer:0},
    {question:"Vilken plattform är känd för korta videor och dansutmaningar?",options:["Facebook","TikTok","Twitter","LinkedIn"],correctAnswer:1},
    {question:"Vilket rockband släppte 'The Dark Side of the Moon'?",options:["The Beatles","Led Zeppelin","Pink Floyd","The Rolling Stones"],correctAnswer:2},
    {question:"Vem skrev böckerna om Sagan om Ringen?",options:["C.S. Lewis","J.K. Rowling","George R.R. Martin","J.R.R. Tolkien"],correctAnswer:3},
    {question:"Vad heter den tecknade svampen som bor i en ananas?",options:["Patrick Stjärna","SvampBob Fyrkant","Bläckvard","Sandy Cheeks"],correctAnswer:1},
    {question:"Vilken skådespelerska spelade i Friends och var gift med Brad Pitt?",options:["Courteney Cox","Lisa Kudrow","Jennifer Aniston","Angelina Jolie"],correctAnswer:2},
    {question:"Vad heter den kända musikalen med ABBA-låtar?",options:["Cats","Les Misérables","Mamma Mia!","Phantom of the Opera"],correctAnswer:2},
    {question:"Vilken superhjälte kommer från planeten Krypton?",options:["Batman","Spider-Man","Thor","Stålmannen"],correctAnswer:3},
    {question:"Vad dricker James Bond helst?",options:["Martini, skakad inte rörd","Whisky on the rocks","En kall öl","Gin och tonic"],correctAnswer:0},
    {question:"Vilket band frontades av Kurt Cobain?",options:["Pearl Jam","Soundgarden","Alice in Chains","Nirvana"],correctAnswer:3},
    {question:"Vem spelar Wednesday Addams i Netflix-serien?",options:["Christina Ricci","Jenna Ortega","Millie Bobby Brown","Zendaya"],correctAnswer:1},
    {question:"Vilken artist är känd för alter egot 'Slim Shady'?",options:["Snoop Dogg","Eminem","Jay-Z","Kanye West"],correctAnswer:1},
    {question:"Vad heter åskguden i Marvel?",options:["Loki","Odin","Thor","Hulk"],correctAnswer:2},
    {question:"Vilken film vann flest Oscars 2024?",options:["Barbie","Oppenheimer","Killers of the Flower Moon","Poor Things"],correctAnswer:1},
    {question:"Vilket tv-program leds av Gordon Ramsay?",options:["MasterChef","Hell's Kitchen","Chopped","Bake Off"],correctAnswer:1},
    {question:"Vilken artist framförde 'Blinding Lights'?",options:["Bruno Mars","The Weeknd","Justin Bieber","Drake"],correctAnswer:1},
    {question:"Vilket k-pop-band har fans som kallas 'ARMY'?",options:["BLACKPINK","EXO","BTS","Stray Kids"],correctAnswer:2},
    {question:"Vad hette Ryan Goslings karaktär i filmen Barbie?",options:["Ken","Allan","Bob","Max"],correctAnswer:0},
    {question:"Vem sjöng 'My Heart Will Go On' i Titanic?",options:["Whitney Houston","Celine Dion","Mariah Carey","Enya"],correctAnswer:1},
    {question:"I vilken stad utspelar sig Gossip Girl?",options:["Los Angeles","London","New York","Paris"],correctAnswer:2},
    {question:"Vem är gift med Beyoncé?",options:["P Diddy","Kanye West","Jay-Z","Pharrell Williams"],correctAnswer:2},
    {question:"Vad heter rymdskeppet i Alien-filmerna?",options:["Millennium Falcon","Nostromo","Enterprise","Discovery"],correctAnswer:1},
    {question:"Vilken känd svensk DJ gick bort 2018?",options:["Alesso","Avicii","Steve Angello","Eric Prydz"],correctAnswer:1},
    {question:"Vem gör rösten till Woody i Toy Story?",options:["Tim Allen","Tom Hanks","Robin Williams","Billy Crystal"],correctAnswer:1},
    {question:"Vilken serie har Michael Scott och Dwight Schrute?",options:["Parks and Recreation","The Office","Friends","Brooklyn Nine-Nine"],correctAnswer:1},
    {question:"Vilken popstjärna befriades från sitt förmynderskap 2021?",options:["Amanda Bynes","Lindsay Lohan","Britney Spears","Paris Hilton"],correctAnswer:2},
    {question:"Vem regisserade Avatar och Terminator 2?",options:["James Cameron","Ridley Scott","Peter Jackson","Steven Spielberg"],correctAnswer:0},
    {question:"Vilken Queen-låt blev film med Rami Malek?",options:["We Will Rock You","Bohemian Rhapsody","Don't Stop Me Now","Radio Ga Ga"],correctAnswer:1},
    {question:"Vad kallas Baby Yoda egentligen i The Mandalorian?",options:["Grogu","Yaddle","Mando","Din Djarin"],correctAnswer:0},
    {question:"Vilken artist släppte albumet 'Midnights' 2022?",options:["Olivia Rodrigo","Billie Eilish","Dua Lipa","Taylor Swift"],correctAnswer:3},
    {question:"Vad heter den kända skräckförfattaren bakom 'Det'?",options:["Dean Koontz","H.P. Lovecraft","Stephen King","Edgar Allan Poe"],correctAnswer:2},
    {question:"Vilken brittisk skådespelare spelar Sherlock i BBC-serien?",options:["Martin Freeman","Benedict Cumberbatch","Tom Hiddleston","David Tennant"],correctAnswer:1},
    {question:"Vem är värd för The Tonight Show i USA?",options:["Jimmy Kimmel","Stephen Colbert","Jimmy Fallon","Conan O'Brien"],correctAnswer:2},
    {question:"I vilken franchise hittar vi 'The Hunger Games'?",options:["Harry Potter","Divergent","Hungerspelen","Maze Runner"],correctAnswer:2}
  ],
  fotboll: [
    {question:"Vem har vunnit flest Ballon d'Or?",options:["Cristiano Ronaldo","Lionel Messi","Pelé","Diego Maradona"],correctAnswer:1},
    {question:"Vilket land vann herrarnas VM 2022?",options:["Frankrike","Brasilien","Argentina","Tyskland"],correctAnswer:2},
    {question:"Vilken spelare har gjort flest mål i svenska herrlandslaget?",options:["Henrik Larsson","Gunnar Nordahl","Sven Rydell","Zlatan Ibrahimovic"],correctAnswer:3},
    {question:"Vilket lag spelar på Anfield?",options:["Everton","Manchester United","Arsenal","Liverpool"],correctAnswer:3},
    {question:"Vad kallas mötet mellan Barcelona och Real Madrid?",options:["Derby della Madonnina","El Clásico","Superclásico","O Classico"],correctAnswer:1},
    {question:"Vilken klubb har vunnit Champions League flest gånger?",options:["AC Milan","Bayern München","Liverpool","Real Madrid"],correctAnswer:3},
    {question:"Vilket land vann det första VM:et 1930?",options:["Argentina","Brasilien","Uruguay","Italien"],correctAnswer:2},
    {question:"Vem tränar Manchester City (2024)?",options:["Jürgen Klopp","Pep Guardiola","Mikel Arteta","Carlo Ancelotti"],correctAnswer:1},
    {question:"Vilken svensk klubb har flest SM-guld?",options:["IFK Göteborg","Malmö FF","AIK","Djurgårdens IF"],correctAnswer:1},
    {question:"Vad heter engelska högstaligan?",options:["La Liga","Serie A","Premier League","Bundesliga"],correctAnswer:2},
    {question:"Vilken spelare köptes av PSG från Barcelona 2017?",options:["Kylian Mbappé","Neymar","Lionel Messi","Luis Suárez"],correctAnswer:1},
    {question:"Vilket nummer bar Diego Maradona?",options:["7","9","10","11"],correctAnswer:2},
    {question:"Vilken nation vann damernas VM 2023?",options:["USA","England","Spanien","Sverige"],correctAnswer:2},
    {question:"Vilken målvakt har flest hållna nollor i Premier League?",options:["Petr Cech","Peter Schmeichel","David de Gea","Ederson"],correctAnswer:0},
    {question:"Vilken tysk klubb spelar på Allianz Arena?",options:["Borussia Dortmund","Bayern München","Bayer Leverkusen","RB Leipzig"],correctAnswer:1},
    {question:"Vem är tidernas främste målskytt i VM för herrar?",options:["Ronaldo (Brasilien)","Gerd Müller","Miroslav Klose","Pelé"],correctAnswer:2},
    {question:"Vilket svenskt lag spelade Europacupfinal 1979?",options:["IFK Norrköping","Malmö FF","IFK Göteborg","Helsingborgs IF"],correctAnswer:1},
    {question:"Vad är färgerna på Juventus hemmatröjor?",options:["Röd och svart","Blå och svart","Vit och svart","Gul och röd"],correctAnswer:2},
    {question:"I vilket land spelades herrarnas EM 2024?",options:["Frankrike","Tyskland","Italien","Spanien"],correctAnswer:1},
    {question:"Vem vann Guldbollen i Sverige flest gånger?",options:["Henrik Larsson","Fredrik Ljungberg","Zlatan Ibrahimovic","Victor Nilsson Lindelöf"],correctAnswer:2},
    {question:"Vilken London-klubb kallas 'The Gunners'?",options:["Chelsea","Tottenham","West Ham","Arsenal"],correctAnswer:3},
    {question:"Vilket år tog svenska herrlandslaget brons i VM?",options:["1958","1990","1994","2002"],correctAnswer:2},
    {question:"Vem gjorde 'Guds hand'-målet 1986?",options:["Pelé","Diego Maradona","Michel Platini","Zico"],correctAnswer:1},
    {question:"Vilken klubb har hemmastadion Old Trafford?",options:["Arsenal","Manchester City","Manchester United","Chelsea"],correctAnswer:2},
    {question:"Vem var förbundskapten under VM 1994?",options:["Lars Lagerbäck","Erik Hamrén","Tommy Svensson","Janne Andersson"],correctAnswer:2},
    {question:"Vilken liga spelar Real Madrid och Barcelona i?",options:["Premier League","Serie A","Bundesliga","La Liga"],correctAnswer:3},
    {question:"Vem är känd som 'Il Capitano' i AS Roma?",options:["Alessandro Del Piero","Paolo Maldini","Francesco Totti","Roberto Baggio"],correctAnswer:2},
    {question:"Vilket afrikanskt lag nådde semifinal i VM 2022?",options:["Senegal","Marocko","Ghana","Kamerun"],correctAnswer:1},
    {question:"Vem gjorde det avgörande målet i VM-finalen 2014?",options:["Thomas Müller","Toni Kroos","Mario Götze","Bastian Schweinsteiger"],correctAnswer:2},
    {question:"Vilken fransk spelare vann Ballon d'Or 2022?",options:["Kylian Mbappé","Antoine Griezmann","Karim Benzema","N'Golo Kanté"],correctAnswer:2},
    {question:"Vilket djur finns på engelska landslagets emblem?",options:["Örn","Lejon","Bulldogg","Tupp"],correctAnswer:1},
    {question:"Vilken stadion används för FA-cupfinalen?",options:["Wembley","Old Trafford","Anfield","Stamford Bridge"],correctAnswer:0},
    {question:"Vilken spelare kallas 'El Pistolero'?",options:["Sergio Agüero","Luis Suárez","Edinson Cavani","Alexis Sánchez"],correctAnswer:1},
    {question:"Vilket landslag har vunnit flest herr-VM?",options:["Tyskland","Italien","Argentina","Brasilien"],correctAnswer:3},
    {question:"I vilken stad spelar Aston Villa?",options:["London","Manchester","Birmingham","Liverpool"],correctAnswer:2},
    {question:"Vem har smeknamnet 'The Special One'?",options:["Pep Guardiola","Jürgen Klopp","José Mourinho","Arsène Wenger"],correctAnswer:2},
    {question:"Vilken position spelade Lev Jasjin?",options:["Anfallare","Mittfältare","Försvarare","Målvakt"],correctAnswer:3},
    {question:"Vilket av följande lag spelar i grönt och vitt?",options:["Celtic","Rangers","Aberdeen","Hearts"],correctAnswer:0},
    {question:"Vilken spelare värvades till Al Nassr i början av 2023?",options:["Lionel Messi","Karim Benzema","Cristiano Ronaldo","Neymar"],correctAnswer:2},
    {question:"Vad heter arenan där FC Barcelona spelar?",options:["Santiago Bernabéu","Camp Nou","Wanda Metropolitano","Mestalla"],correctAnswer:1},
    {question:"Vilket märke gör Champions League-bollen?",options:["Nike","Puma","Adidas","Under Armour"],correctAnswer:2},
    {question:"Vilket land representerar Erling Haaland?",options:["Sverige","Danmark","Island","Norge"],correctAnswer:3},
    {question:"Vem gjorde fem mål på nio minuter i Bundesliga 2015?",options:["Aubameyang","Robert Lewandowski","Thomas Müller","Marco Reus"],correctAnswer:1},
    {question:"Hur många spelare har ett fotbollslag på planen?",options:["10","11","12","15"],correctAnswer:1},
    {question:"Vem har rekordet för flest mål i Champions League?",options:["Lionel Messi","Robert Lewandowski","Cristiano Ronaldo","Raúl"],correctAnswer:2},
    {question:"Vilken spelare kallas 'CR7'?",options:["Carlos Ruiz","Cristiano Ronaldo","Casemiro","Cesc Fàbregas"],correctAnswer:1},
    {question:"Vad heter Ballon d'Or-priset för unga spelare?",options:["Golden Boy","Kopa Trophy","Best Young Player","Rising Star"],correctAnswer:1},
    {question:"Vilket lag vann första Premier League-säsongen 1992-93?",options:["Arsenal","Liverpool","Manchester United","Blackburn"],correctAnswer:2},
    {question:"Vilken stad har lag som heter Inter och AC?",options:["Madrid","London","Milano","Manchester"],correctAnswer:2},
    {question:"Vad kallas det när en spelare gör tre mål i en match?",options:["Dubbel","Hattrick","Pokal","Trepoäng"],correctAnswer:1}
  ],
  gaming: [
    {question:"Vilket företag skapade PlayStation?",options:["Microsoft","Nintendo","Sega","Sony"],correctAnswer:3},
    {question:"Vad heter huvudpersonen i The Legend of Zelda?",options:["Zelda","Ganon","Link","Sheik"],correctAnswer:2},
    {question:"I vilket spel hoppar man ur en 'Battle Bus'?",options:["Apex Legends","PUBG","Call of Duty: Warzone","Fortnite"],correctAnswer:3},
    {question:"Vad heter det mest framgångsrika blockbyggarspelet?",options:["Terraria","Roblox","Minecraft","Lego Worlds"],correctAnswer:2},
    {question:"Vad står 'RPG' för inom gaming?",options:["Run, Play, Go","Role-Playing Game","Real Player Graphics","Random Playing Game"],correctAnswer:1},
    {question:"Vad heter den kända rörmokaren i Nintendos spel?",options:["Luigi","Wario","Mario","Toad"],correctAnswer:2},
    {question:"Vilket år släpptes World of Warcraft?",options:["2001","2004","2006","2008"],correctAnswer:1},
    {question:"Vilket spel handlar om staden Los Santos?",options:["Watch Dogs","Saints Row","Grand Theft Auto: San Andreas","Mafia"],correctAnswer:2},
    {question:"Vad kallas CS:GO nuförtiden?",options:["CS:Source","CS 1.6","Counter-Strike 2","CS:Valorant"],correctAnswer:2},
    {question:"Vad heter företaget bakom League of Legends?",options:["Valve","Riot Games","Blizzard","Epic Games"],correctAnswer:1},
    {question:"Vilken färg har Sonic the Hedgehog?",options:["Röd","Gul","Grön","Blå"],correctAnswer:3},
    {question:"Vad heter Master Chiefs AI-kompanjon i Halo?",options:["Siri","Alexa","Cortana","GLaDOS"],correctAnswer:2},
    {question:"Vilken studio utvecklade The Witcher 3?",options:["Bethesda","CD Projekt Red","BioWare","Ubisoft"],correctAnswer:1},
    {question:"Vad måste du akta dig för på natten i Minecraft?",options:["Creeper","Goomba","Ghouls","Murlocs"],correctAnswer:0},
    {question:"Vilket av dessa spel utvecklades i Sverige?",options:["Angry Birds","Candy Crush Saga","Clash of Clans","Tetris"],correctAnswer:1},
    {question:"Vad heter Kratos son i God of War (2018)?",options:["Baldur","Thor","Atreus","Odin"],correctAnswer:2},
    {question:"I vilket spel är 'The Cake is a Lie' ett känt citat?",options:["Half-Life","Portal","Team Fortress 2","Left 4 Dead"],correctAnswer:1},
    {question:"Vad kallas valutan i The Sims?",options:["Simoleans","Credits","V-Bucks","Robux"],correctAnswer:0},
    {question:"Vilken konsol är en hybrid (bärbar och stationär)?",options:["PS5","Xbox Series X","Nintendo Switch","Steam Deck"],correctAnswer:2},
    {question:"Vad heter staden i Resident Evil 2?",options:["Silent Hill","Raccoon City","Midgar","Vice City"],correctAnswer:1},
    {question:"Vilket spel vann Game of the Year 2022?",options:["God of War Ragnarök","Elden Ring","Horizon Forbidden West","Stray"],correctAnswer:1},
    {question:"Vad kallas spökena i Pac-Man?",options:["Inky, Blinky, Pinky och Clyde","Huey, Dewey, Louie och Webby","Dash, Flash, Crash och Bash","Alpha, Beta, Gamma och Delta"],correctAnswer:0},
    {question:"Vilket svenskt e-sportlag hade GeT_RiGhT?",options:["Fnatic","NiP","Godsent","Alliance"],correctAnswer:1},
    {question:"Vad heter spelmotorn som Epic Games utvecklar?",options:["Unity","Source","Unreal Engine","CryEngine"],correctAnswer:2},
    {question:"Vilket djur är Donkey Kong?",options:["Björn","Gorilla","Orangutang","Chimpans"],correctAnswer:1},
    {question:"Vilken genre är Dota 2?",options:["FPS","RTS","MOBA","MMORPG"],correctAnswer:2},
    {question:"I vilket spel bygger och driver du nöjesfält?",options:["SimCity","RollerCoaster Tycoon","Zoo Tycoon","Cities: Skylines"],correctAnswer:1},
    {question:"Vem skapade Stardew Valley?",options:["Toby Fox","Markus Persson","Eric Barone (ConcernedApe)","Hideo Kojima"],correctAnswer:2},
    {question:"Vilken spelfigur äter 'Wumpa-frukter'?",options:["Crash Bandicoot","Spyro","Rayman","Sonic"],correctAnswer:0},
    {question:"Vad heter uppföljaren till Overwatch?",options:["Overwatch: Origins","Overwatch 2","Overwatch: Retribution","Overwatch Heroes"],correctAnswer:1},
    {question:"Vilket spel har 'Clickers' i en postapokalyptisk värld?",options:["Days Gone","The Last of Us","Resident Evil","Fallout"],correctAnswer:1},
    {question:"Vad heter huvudpersonen i Tomb Raider?",options:["Jill Valentine","Aloy","Lara Croft","Ellie"],correctAnswer:2},
    {question:"Vilken svensk studio ligger bakom Battlefield?",options:["DICE","Massive Entertainment","Avalanche","Starbreeze"],correctAnswer:0},
    {question:"Vilket av följande är INTE en Eeveelution i Pokémon?",options:["Jolteon","Flareon","Vaporeon","Pikacheon"],correctAnswer:3},
    {question:"Vad heter antagonisten i Far Cry 3?",options:["Pagan Min","Joseph Seed","Vaas Montenegro","Anton Castillo"],correctAnswer:2},
    {question:"Vilket spel var ursprungligen en mod av Warcraft 3?",options:["League of Legends","Dota","Smite","Heroes of the Storm"],correctAnswer:1},
    {question:"Vilken stealth-serie skapade Hideo Kojima?",options:["Splinter Cell","Hitman","Metal Gear Solid","Thief"],correctAnswer:2},
    {question:"I vilket spel hittar du Tracer, Winston och Mercy?",options:["Valorant","Apex Legends","Paladins","Overwatch"],correctAnswer:3},
    {question:"Vilket årtionde släpptes Pong?",options:["1960-talet","1970-talet","1980-talet","1990-talet"],correctAnswer:1},
    {question:"Vilken handhållen konsol släppte Nintendo 1989?",options:["Game Boy","Game Gear","Nintendo DS","PlayStation Portable"],correctAnswer:0},
    {question:"Vilket spel handlar om att överleva fem nätter som nattvakt?",options:["Amnesia","Outlast","Five Nights at Freddy's","Slender"],correctAnswer:2},
    {question:"Vilken plattform för PC-spel drivs av Valve?",options:["Origin","Epic Games Store","Uplay","Steam"],correctAnswer:3},
    {question:"I vilket spel kan man vara 'Impostor' eller 'Crewmate'?",options:["Fall Guys","Among Us","Phasmophobia","Garry's Mod"],correctAnswer:1},
    {question:"Vad heter huvudpersonen i Assassin's Creed II?",options:["Altaïr","Connor","Ezio Auditore","Edward Kenway"],correctAnswer:2},
    {question:"Vilken av dessa karaktärer kommer från Street Fighter?",options:["Scorpion","Sub-Zero","Ryu","Jin Kazama"],correctAnswer:2},
    {question:"Vad står 'NPC' för?",options:["Non-Playable Character","New Player Control","Next Phase Combat","No Player Connection"],correctAnswer:0},
    {question:"Vilket spel har en Battle Royale-mode som heter Warzone?",options:["Battlefield","Halo","Call of Duty","Gears of War"],correctAnswer:2},
    {question:"I vilket spel samlar man 'Souls' och dör extremt ofta?",options:["Skyrim","Dark Souls","The Witcher 3","Dragon Age"],correctAnswer:1},
    {question:"Vad heter spelsändningsplattformen som ägs av Amazon?",options:["YouTube Gaming","Mixer","Facebook Gaming","Twitch"],correctAnswer:3},
    {question:"Vem skapade Minecraft?",options:["Notch (Markus Persson)","Gabe Newell","John Carmack","Shigeru Miyamoto"],correctAnswer:0}
  ],
  sverige: [
    {question:"Vad heter Sveriges högsta berg?",options:["Sarektjåkkå","Kebnekaise","Åreskutan","Sylarna"],correctAnswer:1},
    {question:"Vilken dag firas Sveriges nationaldag?",options:["6 juni","1 maj","Midsommarafton","24 december"],correctAnswer:0},
    {question:"Vem är Sveriges kung (2024)?",options:["Carl XVI Gustaf","Gustaf V","Carl Johan","Gustaf VI Adolf"],correctAnswer:0},
    {question:"Vilken stad kallas 'Sveriges framsida'?",options:["Stockholm","Malmö","Göteborg","Helsingborg"],correctAnswer:2},
    {question:"Vad heter Sveriges längsta skidtävling?",options:["Vätternrundan","Vasaloppet","Lidingöloppet","Birkebeinerrennet"],correctAnswer:1},
    {question:"Vilken svensk författare skrev om Pippi Långstrump?",options:["Selma Lagerlöf","Astrid Lindgren","Tove Jansson","Elsa Beskow"],correctAnswer:1},
    {question:"Vad heter Sveriges största sjö?",options:["Vättern","Mälaren","Vänern","Hjälmaren"],correctAnswer:2},
    {question:"Vilket parti har förkortningen 'S'?",options:["Sverigedemokraterna","Socialdemokraterna","Centerpartiet","Miljöpartiet"],correctAnswer:1},
    {question:"I vilken stad ligger Liseberg?",options:["Göteborg","Stockholm","Norrköping","Uppsala"],correctAnswer:0},
    {question:"Vilken svensk musikgrupp vann Eurovision 1974?",options:["Roxette","Ace of Base","ABBA","Europe"],correctAnswer:2},
    {question:"Vilket djur kallas 'Skogens konung'?",options:["Varg","Björn","Älg","Lodjur"],correctAnswer:2},
    {question:"Vem var statsminister när han mördades 1986?",options:["Göran Persson","Tage Erlander","Olof Palme","Carl Bildt"],correctAnswer:2},
    {question:"Vad heter det stora varuhuset i Ullared?",options:["IKEA","Gekås","Åhléns","NK"],correctAnswer:1},
    {question:"Vilken kung regerade under stormaktstiden och dog 1632?",options:["Karl XII","Gustav II Adolf","Gustav Vasa","Johan III"],correctAnswer:1},
    {question:"I vilken ort byggs det berömda ishotellet?",options:["Kiruna","Jukkasjärvi","Gällivare","Abisko"],correctAnswer:1},
    {question:"Vilket möbelföretag grundades av Ingvar Kamprad?",options:["Jysk","Mio","IKEA","Kinnarps"],correctAnswer:2},
    {question:"I vilket landskap ligger Lund och Malmö?",options:["Skåne","Blekinge","Halland","Småland"],correctAnswer:0},
    {question:"Vem skrev 'Nils Holgerssons underbara resa'?",options:["Astrid Lindgren","Selma Lagerlöf","Vilhelm Moberg","August Strindberg"],correctAnswer:1},
    {question:"Vad kallas midsommarstången med ett annat ord?",options:["Majstång","Feststång","Sommarpåle","Kransstång"],correctAnswer:0},
    {question:"Vilken kung genomförde reformationen 1523?",options:["Karl IX","Erik XIV","Gustav Vasa","Johan III"],correctAnswer:2},
    {question:"Vad kallas lagen som ger alla rätt att vistas i naturen?",options:["Allemansrätten","Naturlagen","Skogsrätten","Fritidslagen"],correctAnswer:0},
    {question:"Vilken stad är residensstad i Gotlands län?",options:["Slite","Klintehamn","Visby","Fårösund"],correctAnswer:2},
    {question:"Vilken svensk uppfann dynamiten?",options:["Christopher Polhem","John Ericsson","Alfred Nobel","Gustaf de Laval"],correctAnswer:2},
    {question:"Vad heter det berömda skeppet som sjönk på sin jungfrufärd?",options:["Regalskeppet Kronan","Regalskeppet Vasa","Mars","Svärdet"],correctAnswer:1},
    {question:"Vilken dryck dricks ofta till julmaten?",options:["Påskmust","Julmust","Glögg","Sockerdricka"],correctAnswer:1},
    {question:"Vilken tradition firas den 13 december?",options:["Midsommar","Valborg","Lucia","Kristi Himmelsfärd"],correctAnswer:2},
    {question:"Vad heter Sveriges sydligaste udde?",options:["Treriksröset","Smygehuk","Falsterbo","Sandhammaren"],correctAnswer:1},
    {question:"Vilken är Sveriges minsta fågel?",options:["Blåmes","Kungsfågel","Gråsparv","Bofink"],correctAnswer:1},
    {question:"Vilken av dessa är en känd svensk godissort?",options:["Polkagris","Marsipan","Lakritsbåt","Geléhallon"],correctAnswer:0},
    {question:"Vad heter bron mellan Sverige och Danmark?",options:["Öresundsbron","Svinesundsbron","Höga Kusten-bron","Ölandsbron"],correctAnswer:0},
    {question:"Vad heter den svenska valutan?",options:["Euro","Krona","Mark","Franc"],correctAnswer:1},
    {question:"Vilken stad är Sveriges näst största?",options:["Malmö","Uppsala","Göteborg","Linköping"],correctAnswer:2},
    {question:"Vad heter Sveriges längsta flod?",options:["Dalälven","Torneälven","Klarälven","Göta älv"],correctAnswer:1},
    {question:"Hur många landskap har Sverige?",options:["21","25","29","18"],correctAnswer:1},
    {question:"Vilket svenskt band är känt för 'The Final Countdown'?",options:["Roxette","Ace of Base","Europe","ABBA"],correctAnswer:2},
    {question:"Vad heter Sveriges riksdag?",options:["Stortinget","Riksdagen","Folketinget","Althingi"],correctAnswer:1},
    {question:"Vilken svensk stad är känd för sin domkyrka och universitet?",options:["Lund","Visby","Kalmar","Karlstad"],correctAnswer:0},
    {question:"Vad äter man traditionellt på Fettisdagen?",options:["Våfflor","Semlor","Lussebullar","Kanelbullar"],correctAnswer:1},
    {question:"Vilken ö ligger utanför Stockholms skärgård och har en berömd hamn?",options:["Gotland","Sandhamn","Öland","Vaxholm"],correctAnswer:1},
    {question:"Vem grundade Spotify?",options:["Niklas Zennström","Daniel Ek","Martin Lorentzon","Markus Persson"],correctAnswer:1}
  ]
};

function getQuestionFromCategory(categoryId) {
  if (!categoryId || categoryId === 'blandat') {
    return getRandomQuestion();
  }
  const questions = QUESTIONS[categoryId];
  if (!questions || questions.length === 0) return getRandomQuestion();
  const q = questions[Math.floor(Math.random() * questions.length)];
  const cat = TRIVIA_CATEGORIES.find(c => c.id === categoryId);
  return { ...q, category: cat?.name || categoryId };
}

function getRandomQuestion() {
  const allCategories = Object.keys(QUESTIONS);
  const catId = allCategories[Math.floor(Math.random() * allCategories.length)];
  const questions = QUESTIONS[catId];
  const q = questions[Math.floor(Math.random() * questions.length)];
  const cat = TRIVIA_CATEGORIES.find(c => c.id === catId);
  return { ...q, category: cat?.name || catId };
}
